In [1]:
import numpy as np
import pandas as pd
import networkx as nx

In [2]:
ht_result = pd.read_csv("../result_data/ht_result.csv",index_col=0)
hs_result = pd.read_csv("../result_data/hs_result.csv",index_col=0)

In [3]:
ht_result[['h', 't']] = ht_result["ht"].str.split(",", expand=True)
new_ord = ['h', 't'] + [col for col in ht_result.columns if col not in ['h', 't', 'ht']]
ht_result = ht_result[new_ord]

hs_result[['h', 's']] = hs_result["hs"].str.split(",", expand=True)
new_ord = ['h', 's'] + [col for col in hs_result.columns if col not in ['h', 's', 'hs']]
hs_result = hs_result[new_ord]

In [4]:
ht_result.columns = ['h', 't'] + [x+'2' for x in ht_result.columns if x not in ['h', 't']]

In [ ]:
import pandas as pd

# Sample data
hs_data = {
    'h': [1, 1],
    's': ['A', 'B'],
    'fe1_1': [0.1, 0.2],
    'fe1_2': [0.4, 0.5],
}

ht_data = {
    'h': [1, 1],
    't': ['X', 'Y'],
    'fe2_1': [0.7, 0.8],
    'fe2_2': [1.0, 1.1],
}

# Convert data to pandas DataFrames
hs_df = pd.DataFrame(hs_data)
ht_df = pd.DataFrame(ht_data)

# Merge datasets on 'h'
merged_df = pd.merge(hs_df, ht_df, on='h')

# Create the final dataset with the required columns
final_df = merged_df[['h'] + [f'fe1_{i}' for i in range(1, 3)] + [f'fe2_{i}' for i in range(1, 3)] + ['t']]

# Display the final dataset
print(final_df)

   h  fe1_1  fe1_2  fe2_1  fe2_2  t
0  1    0.1    0.4    0.7    1.0  X
1  1    0.1    0.4    0.8    1.1  Y
2  1    0.2    0.5    0.7    1.0  X
3  1    0.2    0.5    0.8    1.1  Y

In [5]:
# Merge datasets on 'h'
merged_df = pd.merge(hs_result, ht_result, on='h')

# Create the final dataset with the required columns
final_df = merged_df[['h'] + [col for col in hs_result.columns if col not in ['h', 's']]\
                    + [col for col in ht_result.columns if col not in ['h', 't']] + ['t']]

# Display the final dataset
final_df

,h,CN,JC,SL,SI,PA,AA,RA,HP,HD,...,HD2,LHN2,PD2,LAS2,CB2,IA2,MI2,FSW2,LNL2,t
0,H1241,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.188571,0.005408,0.000002,0.082914,0.122465,0.156803,0.365699,0.105221,0.308844,P8758
1,H1241,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.232394,0.007084,0.000005,0.085034,0.078843,0.190936,0.322167,0.073072,0.268933,P8651
2,H1241,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.200567,0.005753,0.000002,0.097408,0.188716,0.194366,0.443219,0.164402,0.403430,P8781
3,H1241,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.204392,0.005862,0.000003,0.081598,0.116110,0.096367,0.329800,0.088416,0.279195,P9066
4,H1241,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.198654,0.005698,0.000002,0.105313,0.224267,0.300494,0.505574,0.211160,0.472610,P9282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255963,H1054,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,P9103
1255964,H1054,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,P9867
1255965,H1054,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,P8856
1255966,H1054,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,P10897
1255967,H125,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,P9037

In [6]:
from sklearn.preprocessing import LabelEncoder

h_labelEncode = LabelEncoder().fit(final_df["h"])
t_labelEncode = LabelEncoder().fit(final_df["t"])

final_df['h'] = h_labelEncode.transform(final_df["h"])
final_df['t'] = t_labelEncode.transform(final_df["t"])

C:\Users\Mmli\AppData\Local\Temp\ipykernel_18084\2423403286.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['h'] = h_labelEncode.transform(final_df["h"])
C:\Users\Mmli\AppData\Local\Temp\ipykernel_18084\2423403286.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['t'] = t_labelEncode.transform(final_df["t"])

In [7]:
final_df

,h,CN,JC,SL,SI,PA,AA,RA,HP,HD,...,HD2,LHN2,PD2,LAS2,CB2,IA2,MI2,FSW2,LNL2,t
0,86,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.188571,0.005408,0.000002,0.082914,0.122465,0.156803,0.365699,0.105221,0.308844,800
1,86,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.232394,0.007084,0.000005,0.085034,0.078843,0.190936,0.322167,0.073072,0.268933,718
2,86,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.200567,0.005753,0.000002,0.097408,0.188716,0.194366,0.443219,0.164402,0.403430,820
3,86,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.204392,0.005862,0.000003,0.081598,0.116110,0.096367,0.329800,0.088416,0.279195,1057
4,86,0.130435,0.077775,0.1275,0.107782,0.074044,0.11618,0.072036,0.15283,0.071647,...,0.198654,0.005698,0.000002,0.105313,0.224267,0.300494,0.505574,0.211160,0.472610,1231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255963,29,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,1090
1255964,29,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,1665
1255965,29,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,885
1255966,29,0.000000,0.000000,0.0000,0.000000,0.000608,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,466
1255967,87,0.000000,0.000000,0.0000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050772,0.000000,0.000000,1037

In [67]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.99)
df_pca = pca.fit_transform(final_df.drop(["h", "t"], axis=1))

In [68]:
df_pca.shape

(2551299, 10)

In [8]:
X = pd.concat((final_df['h'], pd.DataFrame(final_df)), axis=1).to_numpy()
y = final_df['t']

In [10]:
len(y.unique())

1757

In [9]:
from sklearn.model_selection import train_test_split

# split into train and test data
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [11]:
X_train

array([[1.51000000e+02, 1.51000000e+02, 3.65217391e-01, ...,
        7.30812245e-04, 6.20599432e-03, 6.63000000e+02],
       [3.34000000e+02, 3.34000000e+02, 2.60869565e-02, ...,
        0.00000000e+00, 0.00000000e+00, 4.40000000e+02],
       [1.97000000e+02, 1.97000000e+02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.24900000e+03],
       ...,
       [7.80000000e+01, 7.80000000e+01, 4.34782609e-01, ...,
        7.30812245e-04, 4.52831429e-02, 1.49800000e+03],
       [1.45000000e+02, 1.45000000e+02, 1.91304348e-01, ...,
        0.00000000e+00, 0.00000000e+00, 1.44100000e+03],
       [7.80000000e+01, 7.80000000e+01, 3.73913043e-01, ...,
        7.30812245e-04, 4.52831429e-02, 1.10000000e+03]])

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Set your parameters
input_size = 36
hidden_size = 64
output_size = 1757
learning_rate = 0.001
batch_size = 64
epochs = 10

# Define the neural network model
model = models.Sequential([
    layers.Dense(hidden_size, activation='relu', input_shape=(input_size,)),
    layers.Dense(output_size, activation='softmax')
])

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate),
              loss='sparse_categorical_crossentropy',  # Use 'categorical_crossentropy' if you one-hot encode your labels
              metrics=['accuracy'])

# Print model summary
model.summary()

# Create a callback to stop training if the validation loss doesn't improve
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# Train the model
history = model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size,
                    validation_data=(X_val, y_val), callbacks=[early_stopping])

# Evaluate on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test Accuracy: {test_accuracy}')