In [1]:
import numpy as np
import pandas as pd
import networkx as nx

In [53]:
ht_result = pd.read_csv("../result_data/ht_result.csv",index_col=0)
hs_result = pd.read_csv("../result_data/hs_result.csv",index_col=0)

In [54]:
ht_result[['h', 't']] = ht_result["ht"].str.split(",", expand=True)
new_ord = ['h', 't'] + [col for col in ht_result.columns if col not in ['h', 't', 'ht']]
ht_result = ht_result[new_ord]

hs_result[['h', 's']] = hs_result["hs"].str.split(",", expand=True)
new_ord = ['h', 's'] + [col for col in hs_result.columns if col not in ['h', 's', 'hs']]
hs_result = hs_result[new_ord]

In [55]:
ht_result.columns = ['h', 't'] + [x+'2' for x in ht_result.columns if x not in ['h', 't']]

In [ ]:
import pandas as pd

# Sample data
hs_data = {
    'h': [1, 1],
    's': ['A', 'B'],
    'fe1_1': [0.1, 0.2],
    'fe1_2': [0.4, 0.5],
}

ht_data = {
    'h': [1, 1],
    't': ['X', 'Y'],
    'fe2_1': [0.7, 0.8],
    'fe2_2': [1.0, 1.1],
}

# Convert data to pandas DataFrames
hs_df = pd.DataFrame(hs_data)
ht_df = pd.DataFrame(ht_data)

# Merge datasets on 'h'
merged_df = pd.merge(hs_df, ht_df, on='h')

# Create the final dataset with the required columns
final_df = merged_df[['h'] + [f'fe1_{i}' for i in range(1, 3)] + [f'fe2_{i}' for i in range(1, 3)] + ['t']]

# Display the final dataset
print(final_df)

   h  fe1_1  fe1_2  fe2_1  fe2_2  t
0  1    0.1    0.4    0.7    1.0  X
1  1    0.1    0.4    0.8    1.1  Y
2  1    0.2    0.5    0.7    1.0  X
3  1    0.2    0.5    0.8    1.1  Y

In [58]:
# Merge datasets on 'h'
merged_df = pd.merge(hs_result, ht_result, on='h')

# Create the final dataset with the required columns
final_df = merged_df[['h'] + [col for col in hs_result.columns if col not in ['h', 's']]\
                    + [col for col in ht_result.columns if col not in ['h', 't']] + ['t']]

# Display the final dataset
final_df

,h,CN,JC,SL,SI,PA,AA,RA,HP,HD,...,HD2,LHN2,PD2,LAS2,CB2,IA2,MI2,FSW2,LNL2,t
0,H1241,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.188571,0.005304,0.000002,0.081957,0.122202,0.157929,0.368518,0.105221,0.309738,P8758.0
1,H1241,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.227901,0.006947,0.000005,0.084237,0.078687,0.192655,0.324451,0.073072,0.269854,P8651.0
2,H1241,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.200567,0.005641,0.000002,0.096212,0.188797,0.195609,0.446441,0.164401,0.403964,P8781.0
3,H1241,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.204392,0.005749,0.000003,0.080721,0.116179,0.096922,0.332204,0.088416,0.279381,P9066.0
4,H1241,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.198654,0.005587,0.000002,0.103958,0.224267,0.303104,0.509357,0.211159,0.473716,P9282.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551294,H448,0.00,0.000000,0.000000,0.000000,0.021858,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,P8771.0
2551295,H125,0.00,0.000000,0.000000,0.000000,0.000212,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,P11025.0
2551296,H125,0.00,0.000000,0.000000,0.000000,0.000212,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,P9037.0
2551297,H125,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,P11025.0
2551298,H125,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,P9037.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

h_labelEncode = LabelEncoder().fit(final_df["h"])
t_labelEncode = LabelEncoder().fit(final_df["t"])

final_df['h'] = h_labelEncode.transform(final_df["h"])
final_df['t'] = t_labelEncode.transform(final_df["t"])

In [63]:
final_df

,h,CN,JC,SL,SI,PA,AA,RA,HP,HD,...,HD2,LHN2,PD2,LAS2,CB2,IA2,MI2,FSW2,LNL2,t
0,103,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.188571,0.005304,0.000002,0.081957,0.122202,0.157929,0.368518,0.105221,0.309738,805
1,103,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.227901,0.006947,0.000005,0.084237,0.078687,0.192655,0.324451,0.073072,0.269854,722
2,103,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.200567,0.005641,0.000002,0.096212,0.188797,0.195609,0.446441,0.164401,0.403964,825
3,103,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.204392,0.005749,0.000003,0.080721,0.116179,0.096922,0.332204,0.088416,0.279381,1062
4,103,0.12,0.074725,0.123261,0.104255,0.066734,0.102363,0.052853,0.14881,0.073123,...,0.198654,0.005587,0.000002,0.103958,0.224267,0.303104,0.509357,0.211159,0.473716,1237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551294,253,0.00,0.000000,0.000000,0.000000,0.021858,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,815
2551295,104,0.00,0.000000,0.000000,0.000000,0.000212,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,534
2551296,104,0.00,0.000000,0.000000,0.000000,0.000212,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,1042
2551297,104,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,534
2551298,104,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.051415,0.000000,0.000000,1042

In [67]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.99)
df_pca = pca.fit_transform(final_df.drop(["h", "t"], axis=1))

In [68]:
df_pca.shape

(2551299, 10)

In [84]:
X = pd.concat((final_df['h'], pd.DataFrame(df_pca)), axis=1).to_numpy()
y = final_df['t']

In [85]:
from sklearn.model_selection import train_test_split

# split into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [86]:
from sklearn.svm import LinearSVC

# train the model
model = LinearSVC()
model.fit(X_train, y_train)

# predict
y_hat = model.predict(X_test)

c:\Users\Mmli\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [ ]:
from sklearn.metrics import f1_score

print(f1_score(y_test, y_hat))

In [82]:
X_train

,h,0,1,2,3,4,5,6,7,8,9
1828603,222,0.524244,0.270524,-0.096937,0.127694,0.009506,0.021468,0.023101,-0.047053,-0.028162,0.015290
102049,201,0.302656,0.413967,0.696083,0.170495,0.154025,0.212237,0.067197,0.268639,-0.123352,0.053248
2381710,323,-0.268992,-0.235730,-0.070252,0.016326,0.055639,-0.013222,0.037585,-0.001940,-0.015694,0.014907
1855978,223,-0.092494,-0.389053,-0.075776,-0.100909,0.170138,0.002940,-0.036940,-0.007751,0.010348,0.009649
1781883,213,-0.154024,0.061532,-0.067204,-0.097777,-0.042061,-0.139863,0.029483,0.065588,0.002545,0.014524
...,...,...,...,...,...,...,...,...,...,...,...
110268,140,-0.379582,-0.055623,0.003083,-0.000750,-0.038273,0.064183,-0.012744,-0.010639,-0.008891,-0.001794
1692743,318,-0.531984,-0.183674,-0.064634,0.061073,-0.035546,-0.013178,0.005578,0.019844,0.026127,-0.006332
2356330,180,0.139657,-0.010385,-0.079040,0.053517,-0.043297,-0.063832,0.116645,0.020711,-0.029783,0.021039
2229084,313,-0.246006,0.145900,-0.071086,-0.104853,-0.026189,-0.063725,-0.016526,0.033909,0.022166,0.005375
2219110,313,-0.020433,-0.091148,-0.067870,-0.005650,-0.025685,-0.164481,0.035879,0.061153,-0.017768,0.023492